### ISSUE TITLE
 length in NewRect(p Point, lengths []float64) may be zero

### ISSUE THREAD

**Issue by warrenwyf** [dhconnelly/rtreego#18]
Consider a point or a line which has the same y coordinates, the length of bounding box may be zero

**Comment by xtuc** [comment]
We ended up adding an epsilon (something like 0,0001) if the box had a 0 lentgh. 

I can make a PR if you're fine with this solution.

**Comment by dhconnelly** [comment]
Sure, I'll happily accept a PR!
