### ISSUE TITLE
NewRectFromPoints should not modify its inputs

### ISSUE THREAD

**Issue by magnushiie** [dhconnelly/rtreego#46]
`NewRectFromPoints` currently [modifies](https://github.com/dhconnelly/rtreego/blob/master/geom.go#L194-L195) its input slices without any warning in the documentation to the caller.

This can result in hours of troubleshooting, as it only happens if some first coordinate is above the second coordinate.

Also consider using value types (arrays) instead of reference types (slices).

**Comment by dhconnelly** [comment]
Yup, it shouldn't modify the inputs. Happy to accept a PR for this! Using arrays is infeasible though as the library intentionally supports runtime-determined dimensionality.

**Comment by dhconnelly** [comment]
something like this would help for using arrays: https://github.com/golang/go/issues/44253
