### ISSUE TITLE
Unclear SearchIntersect Documentation

### ISSUE THREAD

**Issue by minkezhang** [dhconnelly/rtreego#49]
https://go.dev/play/p/pnS0NlILZrm

From the README:
> Bounding-box queries require a search *Rect. It returns all objects that touch the search rectangle.

However, we see from the demo that objects which are adjacent to the query input are not returned.

**Comment by dhconnelly** [comment]
you're right, it should read "It returns all objects whose intersection with the search rectangle has non-zero volume" or something else more specific. happy to accept a PR to clarify!
