### ISSUE TITLE
will you implement R*tree?

### ISSUE THREAD

**Issue by xtaci** [dhconnelly/rtreego#5]
R*Tree has better query performance.

I'm going to use RTree to do multi-dimension information query, instead of  for spatial searching, for example, to query records witch satisfies [type, age, score... etc... ], I think rtree fits well for this situation.

**Comment by dhconnelly** [comment]
I currently have no plans to extend the existing functionality, as my own priorities and interests have moved on in the past few years. I'm very happy to accept pull requests, though, and I'm sure the other clients would be interested in better query performance!

**Comment by xtaci** [comment]
after all, great job! thanks,I've test a 1-million records query, the insertion is relatively slow, and the search speed is around 60~100us in my macbook pro.
