### ISSUE TITLE
not work when dim = 3 

### ISSUE THREAD

**Issue by sunsky303** [dhconnelly/rtreego#51]
rtreego.NewTree(3, 32, 64)}, 
find nearest point should be : lat 30.36424936824087, lon 104.03521157476646 ele 413.5494622178376， 
but it  is :  Loc:[30.36001598001311 104.04658807033596 413.5494622178376]

**Comment by dhconnelly** [comment]
Can you provide a full reproduction case? This isn’t really enough information to be able to reproduce or debug.
