### ISSUE TITLE
No Recent Tag

### ISSUE THREAD

**Issue by benjic** [dhconnelly/rtreego#53]
I noticed master is considerably ahead of the last tag. Is there a reason it hasn't recently been tagged and released?

**Comment by benjic** [comment]
The most recent tag is [v1.1.0](https://github.com/dhconnelly/rtreego/releases/tag/v1.1.0) which is 789 days ago as of today. 😄

**Comment by dhconnelly** [comment]
No, no reason. Just tagged v1.2.0. Thanks for the report 😄
